vibe-d/vibe-core

source/vibe/core/file.d
source/vibe/core/path.d

The previous design, while intended as an improvement over the one-size-fits all Path struct of vibe-d:core, turned out to produce lots of bugs during the transition, because of missing Path.type checks.
The new design uses a cleaner approach, where the static type of a path value encodes the path format. An explicit cast is necessary to convert between different path types. The internet path type also performs proper validation and percent encoding, so that InetPath.toString() always produces a valid URI path.

Redesign the Path type to statically encode the path format.

---

source/vibe/core/log.d

Last week I discovered an imho important use case of `vibe.core.log`: I wanted to display more information on the default console logger (file name, line number, ...) and thought that I can just implement my own logger and deregister the default one. However, unfortunately deregistering the default logger isn't possible as no reference to it is exposed to the user.
An alternative to exposing `getLoggers`, would be to have a `deregisterAll` method.
Btw what is the reason for commenting `string mod = __MODULE__, string func = __FUNCTION__,`?
Did it add too much bloat to the compiled binary?

Allow removal of the default logger

---

source/vibe/internal/allocator.d
source/vibe/internal/hashmap.d

This is required since processAllocator returns an ISharedAlloactor since 2.075.0. Because HashMap is operating only thread-local, this should generally be safe.

Use a thread local allocator instead of processAllocator in HashMap.

---

source/vibe/core/core.d
source/vibe/core/net.d

Analogous to https://github.com/rejectedsoftware/vibe.d/pull/1811
> This was probably not seen because no developers actively compiles Vibe.d on Windows and looked at the deprecation warnings.
See also: https://github.com/dlang/phobos/pull/5532

Remove deprecated stdc import

---

source/vibe/core/task.d
source/vibe/core/taskpool.d

Fixes "dwarfeh(224) fatal error" that are suspected to be related to occasional infinite loops.

Use abort() in case of uncaught Error exceptions.

---

source/vibe/core/file.d
source/vibe/core/sync.d
source/vibe/core/task.d
source/vibe/internal/allocator.d
source/vibe/internal/list.d

Recent production tests lead to some hangs/crashes that haven't been caught by the (randomized or deterministic) unit tests. This adds assertions to detect invalid states earlier and the matching fixes to the observed bugs.

Improve  and fix (Local)ManualEvent

---

source/vibe/core/sync.d

Got some nasty deadlocks in connection pool because of this.

fix deadlocks, caused by second m_locks increment

---

source/vibe/core/core.d
source/vibe/core/net.d
source/vibe/core/sync.d
source/vibe/internal/async.d
source/vibe/internal/list.d

A first profiling run showed that every call to `asyncAwait` produced three to four heap closures, due to the way the different callbacks were wrapped. This change eliminates all of these to make room for more performance tuning.

Convert Waitable from struct to pure template to avoid heap closures.

---

dub.sdl
source/vibe/internal/allocator.d

As discussed before, `stdx-allocator` is a frozen version of std.experimental.allocator to avoid the frequent breakages. 
See also: https://github.com/dlang-community/discussions/issues/27

Use the stable stdx-allocator DUB package

---

source/vibe/core/net.d
source/vibe/core/stream.d

- also see [15130 – dmd emits huge data for zero initialized struct](https://issues.dlang.org/show_bug.cgi?id=15130)

avoid Buffer type which creates a huge __initZ symbol

---

source/vibe/core/net.d

Let the method return more than just 0 or 1

Fix incorrect return value in TCPConnection.leastSize()

---

source/vibe/core/net.d

I have implemented your suggested changes and I am hoping that we can discuss this PR more if needed.

TCPConnection.waitForDataAsync 

---

source/vibe/core/core.d
tests/issue-66-yield-eventloop-exit.d

Idle processing needs to check whether there are still tasks scheduled to be resumed before setting the exit flag when there are no more waiters (I/O etc.). Fixes #66.

 Don't exit event loop prematurely.

---

CHANGELOG.md
source/vibe/core/core.d
source/vibe/core/net.d

If the lambda is a concrete function, two different versions will end up for it in the final binary on macOS when compiled with LDC. Using argument inference works around that issue.

Ensure async lambdas are templates to fix LDC linker errors. Fixes #65.

---

source/vibe/core/args.d

See https://github.com/vibe-d/vibe.d/pull/1916

Re-introduced setCommandLineArgs from vibe-d:core-0.8.2 (pull/1916)

---

dub.sdl
source/vibe/core/core.d
source/vibe/core/file.d
source/vibe/core/internal/release.d
source/vibe/core/net.d
source/vibe/core/sync.d

This change modifies destructors to anticipate that they can be called form a foreign thread if the GC is involved. The actual release of the reference will then happen deferred in the original thread.

Allow destructors to run in foreign threads. Fixes #69.

---

source/vibe/core/core.d
source/vibe/core/task.d

The status of the task was erroneously reported as not running until the task was actually executed for the first time (which only happens after the yield lock has been lifted).

Fix Task.running and Task.yield directly after runTask/yieldLock.

---

source/vibe/core/taskpool.d

This slightly reduces the overhead of task pool threads and simplifies stack traces in case of errors.

Avoid starting an explicit event loop in worker threads.

---

CHANGELOG.md
dub.sdl
source/vibe/core/core.d

In the previous implementation, the callback tasks were starving as soon as the last external reference to a non-pending timer was given up.

Implement callback based timers without relying on a task. Fixes #86.

---

source/vibe/core/core.d
source/vibe/core/sync.d

Since the signal handler can be called in any thread of the application, it may happen so in a non-D thread where Thread.getThis() returns null. This change works around this and also removes the need to call SpinLock.setup on thread startup.

Fix assertion in SpinLock when called from a signal handler.

---

source/vibe/core/args.d

- "key" in JSONValue returns const(JSONValue)*
- fromValue expected non-const JSONValue
- implicit conversion of const(JSONValue) to JSONValue to be fixed
with https://github.com/dlang/phobos/pull/6716

fix relying on implicit const conversion of JSONValue

---

source/vibe/core/net.d
tests/issue-110-close-while-waitForData.d

when m_socket is StreamSocketFD.invalid (which only is set when constructed or when closing) then treat the waitForData result as cancelled.
fix #110

Make waitForData not assert fail on close fix #110

---

source/vibe/core/net.d
tests/issue-115-connect-fail-leak.d

fix #115 
Unsure how this affects windows, ~~but if the auto tests are also run on windows it should find any issue there.~~ please test manually
status is refused in this case and it's not handled by the existing cases cancelling a connection, so the reference to the socket still exists and needs to be released by the caller here.

release ref on failing connectTCP

---

source/vibe/core/channel.d
source/vibe/internal/array.d

Sketches a Channel class, similar to Go's channels, to enable CSP style programming. They are also more efficient than the dynamically typed message queues used by `std.concurrency`.
The basic functionality is there, but various design questions are still unresolved.

Implement typed cross-task channels

---

source/vibe/core/net.d

It seems when running in a vibe-d app listening to HTTP requests that the assert fails. Even though I would like there to be a check, closing the vibe.d app afterwards shows no leaked handles so I think it's fine, and definitely better than not starting anymore at all.

remove refsLeft assert

---

source/vibe/core/core.d

`runApplication` takes an `args_out` parameter which, if non-null, is supposed to be set to match unrecognized command-line args.  However, the parameter is never passed to `finalizeCommandLineOptions`, which will therefore log an error and throw an exception if any command line arguments are unrecognized.
This patch fixes the oversight, ensuring that `runApplication` will correctly populate a non-null `args_out` parameter with unrecognized command-line arguments, and not throw an exception in this case.

Fix runApplication handling of unrecognized command-line args

---

source/vibe/core/file.d

Needed on POSIX systems to recognize special files (isFile and isDir are both false in this case). Same API as std.file.
edit: references https://github.com/vibe-d/vibe-core/issues/132

support isFile

---

source/vibe/core/connectionpool.d

Allows to disconnect all connections that are not currently in use. In particular, it allows to close all connections at shutdown to avoid leaking socket descriptors.

Add ConnectionPool.removeUnused.

---

source/vibe/core/log.d

At various software it is found very big amount of logger calls where is only single string variable used as an argument.
But if somewhere is `logInfo(someGeneratedMsg);` called and `someGeneratedMsg` contains % escape sequence it will be thrown exception.
PR fixes this issue.

Logger: avoid formatting for strings without additional args

---

source/vibe/core/net.d

This integrates with recent event core `reuseAddress` flag.
It allows one to selectively disable those flags.

Add way to disable port and address reuse

---

source/vibe/core/log.d

Logs an exception along with an error message and the full stack trace. Performs proper exception handling for the latter to stay nothrow.

Implement logException.

---

source/vibe/core/process.d
tests/vibe.core.process.d

I've tried to keep most of the features of std.process, if there's anything big I missed let me know.
The tests are simple ports from [supervised](https://github.com/BenjaminSchaaf/supervised). They don't have full coverage, but the core should be solid.

Implement vibe.core.process for subprocess handling similar to std.process

---

source/vibe/core/internal/release.d

Instead of crashing, this now prints a warning message. See #135.

Handle terminated eventcore drivers gracefully when releasing handles.

---

source/vibe/core/concurrency.d
source/vibe/core/core.d
source/vibe/core/file.d
source/vibe/core/taskpool.d

There are currently some file operations (existsFile, getFileInfo, listDirectory) that are directly implemented using the blocking standard library functionality. To avoid stalling the event loop, these are now run in worker tasks.
As a preparatory step, some concurrency functions have been fixed to be `@safe`.

Avoid all blocking file operations outside of worker threads

---

source/vibe/core/file.d
tests/vibe.core.file.d

Instead of asyncWork, now uses a worker task directly and signals the finalization of the result using message passing. This avoids the roundtrip required to return the task handle, as well as the heap allocated result buffer of Future!T.

Fix getFileInfo's exception handling and reduce overhead of the background work.

---

.travis.yml
source/vibe/core/args.d

CC @s-ludwig : I was thinking of doing the same to Vibe.d, as the CI nowadays takes half a day for a single PR.

Clean up std.json deprecation, remove DUB hack in CI

---

source/vibe/core/sync.d
source/vibe/core/task.d
source/vibe/core/taskpool.d

The places that used it showed too much contention in load tests, so that the spin lock was more expensive that the regular OS mutex/futex.

Remove SpinLock and use core.sync.mutex.Mutex instead.

---

source/vibe/internal/allocator.d

Combining GC allocated classes with ref counted structs produces weird bugs in mongo cursors. I would like to use this function in the mongo cursor destructor to better detect if it's called during GC collection

Add a way to enforce that the GC is not running

---

source/vibe/appmain.d
source/vibe/core/args.d
source/vibe/core/channel.d
source/vibe/core/concurrency.d
source/vibe/core/connectionpool.d
source/vibe/core/core.d
source/vibe/core/file.d
source/vibe/core/log.d
source/vibe/core/net.d
source/vibe/core/stream.d
source/vibe/core/task.d
source/vibe/core/taskpool.d
source/vibe/internal/array.d
source/vibe/internal/freelistref.d
source/vibe/internal/hashmap.d
source/vibe/internal/string.d
source/vibe/internal/traits.d
source/vibe/internal/typetuple.d

rejectedsoftware e.K. doesn't exist anymore since mid-2019.

Correct copyright holder.

---

source/vibe/core/core.d
source/vibe/core/task.d
source/vibe/core/taskpool.d
tests/issue-161-multiple-joiners.d

1. Removes the marker task used by schedule() and instead limits the number of task resumptions to the initial length of the task queue
2. Assigns a static and a dynamic priority to each task. The dynamic priority starts with the same value as the static priority and gets incremented by the static priority each time the task gets overtaken by a higher priority task, eventually leading to the task becoming the highest priority (unless the static priority is zero). Tasks with a higher dynamic priority generally take precedence, unless the concurrency exceeds 10 scheduled tasks, in which case the front of the queue is scheduled in normal FIFO order.

Implement priority based task scheduling.

---

.travis.yml

Since LDC v1.9.0 and v1.14.0 are consistently failing, remove them from the CI.
It's not my preferred solution to remove a failing test, but no one seems interested in fixing this (master has been red for over 2 months), and it seems to be an LDC specific issue (so not a language thing).
See commit-per-commit for an explanation of the whats and whys.

Update list of supported compilers

---

source/vibe/internal/freelistref.d

This function wasn't used anymore, but still imported, despite being deprecated.
It was scheduled to be removed a few releases ago (see dlang/phobos#7545).

Remove unused import to enforceEx

---

source/vibe/internal/traits.d

```
As explained in details in dlang/dmd#11000 and dlang/dmd#11474,
'in' has been for a very long time lowered to simply 'const',
or 'scope const' when v2.092.0's '-preview=in' switch is used.
DMD PR 11474 aims to change this, so 'in' is not (visibly)
lowered, and shows up in any user-visible string.
This includes header generation, error messages, and stringof.
Since this code was testing stringof directly, it is affected
by the change. To support testing of both aforementioned DMD PRs,
the change is not tied to a version,
but uses the (soon-to-be) old way as a fallback.
```
Supporting https://github.com/dlang/dmd/pull/11474
@s-ludwig : Can I get a minor release with this (I can do it myself if that's okay with you).

Change a unittest that test for 'in' => 'const' lowering

---

source/vibe/internal/traits.d

Currently those trigger deprecations messages.
Since they are just used in unittests, it doesn't affect client code.

Add 'return' annotations to some tests

---

source/vibe/internal/traits.d

```
Using backtips in the message of a static assert means that
the message will get the same syntax highlight as a compiler error message.
```
Before (when adding `dflags "-dip1000"` to `dub.sdl):
After:

Improve error messages for unimplemented interfaces

---

source/vibe/core/file.d

The file I/O versions of cancelRead and cancelWrite in eventcore currently do not reliably cancel the operation in a synchronous fashion, leading to continued buffer accesses after the cancellation call. In case of the Windows version, this also means that the OVERLAPPED structure can be illegally reused for the next operation, while the previous one hasn't been canceled, yet.
A solution to this issue may require a fundamental change in the file I/O API of eventcore, and the optimal design of that still needs to be worked out. For this reason, we simply avoid using the cancellation functions in vibe-core for now to avoid memory corruption issues. This does mean that interrupting a task that does file I/O won't work anymore.

Work around critical issue in eventcore's cancelRead/cancelWrite.

---

source/vibe/core/net.d

`IOMode.once` causes the `read()` call to return with `IOStatus.wouldBlock` immediately, which previously resulted in erroneously reporting `WaitForDataStatus.noModeData` instead of `timeout`.
See vibe-d/vibe.d#2483

Fix waitForDataEx's return value for an open connection and a zero timeout

---

source/vibe/internal/interfaceproxy.d

Fixes a deprecation warning for ProxyStream.

Avoid instantiating emplace(O) for class instances

---

source/vibe/core/sync.d
source/vibe/core/taskpool.d

Fixes new tasks being able to be scheduled on a worker thread while a busy task (that periodically calls yield()) is running.

Fix a worker task scheduling issue for busy worker tasks.

---

source/vibe/core/channel.d
source/vibe/core/log.d

Adds a low-overhead mode to Channel!T that causes the buffer to be fully processed before notifying waiting peers instead of notifying immediately once data/space is available. This heavily reduces the overhead of cross-task/thread notifications at the expense of introducing processing latency and requiring a call to close() to guarantee that all data has been processed.

Introduce ChannelConfig/ChannelPriority.

---

dub.sdl
source/vibe/core/channel.d
source/vibe/core/file.d
source/vibe/core/log.d

- Directly uses OS facilities instead of Phobos to avoid string processing overhead and to enable fast skipping of non-directories
- Introduces a DirectoryListMode, similar to SpanMode
- Uses low-overhead channels to reduce the communication overhead between the calling thread and the worker thread that calls the OS
- Adds FileInfo.path to properly support the new recursive directory iteration schemes
Note that this should only be merged once #241 is merged and this is rebased.

Rework the listDirectory implementation

---

source/vibe/core/path.d
source/vibe/internal/traits.d

In contrast to `std.path`, these work with pure forward ranges and directly accept `GenericPath` and `GenericPath.Segment(2)`.

Add extension and stripExtension functions

---

source/vibe/core/file.d

Fix compilation of the directory iteration code on additional POSIX based platforms

---

source/vibe/core/taskpool.d

Qualified name `vibe.core.sync.Monitor` is not really available just `Monitor`.
However, for some reason `Monitor` is conflicting with `Object.Monitor` so I had to rename it.
* [DMD bug](https://github.com/dlang/dmd/pull/12215)

Remove a fully-qualified expression that relies on a DMD bug

---

.github/workflows/test.yml
source/vibe/core/sync.d

```
vibe-core ~master: building configuration "vibe-core-test-cfrunloop"...
source/vibe/core/sync.d(214,2): Deprecation: `vibe.core.sync.LocalTaskSemaphore.this` has stricter attributes than its destructor (`@system`)
source/vibe/core/sync.d(214,2):        The destructor will be called if an exception is thrown
source/vibe/core/sync.d(214,2):        Either make the constructor `nothrow` or adjust the field destructors
```

Make LocalTaskSemaphore.this nothrow

---

source/vibe/core/file.d

Allows to skip certain sub directories during a recursive scan.

Add a sub-directory predicate parameter to listDirectory

---

source/vibe/core/file.d

Fix #269 to allow native arm64 compiled version to link with system files on Apple M1/Big Sur.

Fixed fstatat linking on macOS/Apple M1 combination.

---

source/vibe/core/process.d
tests/issue-267-pipe.d

Basically direct use of what is `std.process.pipe()` using [internally](https://github.com/dlang/phobos/blob/b2019ebab00cac223a0f2e3ae6104f2290fb3079/std/process.d#L2620) but without intermediate `File`s that causes the problem.
I've tried to add the windows side as well, but it's not supported with eventcore winapi driver anyway.

Fix #267 - don't close `pipe()` filedescriptors before use

---

source/vibe/core/core.d
source/vibe/core/task.d

Defining `debugVersions "VibeRunningTasks"` will record all running tasks along with stack traces from their most recent yield point. Calling `printRunningTasks()` can then be used to dump all active tasks of the calling thread. Note that due to the slow stack trace capturing ((ab)using exceptions), this has a considerable run time overhead.

Add debug mode for recording currently running tasks

---

source/vibe/core/core.d

See also vibe-d/eventcore#178.

Avoid creating unnecessary thread drivers at thread shutdown

---

.github/workflows/test.yml
source/vibe/core/file.d
tests/vibe.core.file.d
travis-ci.sh

I just noticed that `listDirectory` is horribly broken on macOS and that the test suite has been disabled since the switch to GitHub actions. This re-enables the test suite and fixes the regressions.

Re-enable the test suite.

---

source/vibe/core/channel.d
source/vibe/core/concurrency.d
source/vibe/core/core.d
source/vibe/core/sync.d
source/vibe/core/taskpool.d

Not catching an exception thrown from a task function results in the task getting silently terminated. This frequently results in hidden bugs where certain background processes just hang.
Instead of trying to do something more elaborate, such as rethrowing exceptions from `join` (which is not safely possible for worker tasks and cannot be statically enforced anyway), the plan is to simply disallow throwing task functions. Anything else can be layered on top if required.

Deprecate throwing tasks

---

source/vibe/core/file.d

This was erroring out because in and 'const scope ref' are not covariant.

core.file: Fix -preview=in support

---

source/vibe/core/core.d

Ensures that the thread local event loop gets terminated, even if it is currently in an infinite wait state.
Fixed vibe-d/vibe.d#2596

Fix possibly hanging process after SIGINT/SIGTERM.

---

source/vibe/core/log.d
source/vibe/core/sync.d

I was going through the deprecated symbol and see the v2.069 comment, hence the first commit.
The second commit was found because we use `-checkaction=context`, which triggers the following error:
```
/Users/runner/hostedtoolcache/dc/ldc2-36198b36/x64/ldc2-36198b36-osx-x86_64/bin/../import/core/internal/dassert.d(194,36): Error: cannot implicitly convert expression `v.opCast()` of type `bool` to `const(ManualEvent)`
/Users/runner/hostedtoolcache/dc/ldc2-36198b36/x64/ldc2-36198b36-osx-x86_64/bin/../import/core/internal/dassert.d(449,30): Error: template instance `core.internal.dassert.miniFormat!(shared(ManualEvent))` error instantiating
/Users/runner/hostedtoolcache/dc/ldc2-36198b36/x64/ldc2-36198b36-osx-x86_64/bin/../import/core/internal/dassert.d(334,85):        instantiated from here: …
```

Minor compatibility fixes for upcoming release

---

source/vibe/core/concurrency.d
source/vibe/core/task.d
source/vibe/core/taskpool.d

Avoids the use of `std.concurrency` for tasks that don't explicitly use it, resulting in a vast reduction of resource overhead if many tasks are in use.

Task efficiency improvements

---

source/vibe/core/parallelism.d

Avoids relying on the GC to clean up inputs or outputs.

Make parallelMap clean up resources deterministically.

---

source/vibe/core/net.d

Fix the new deprecation warning.
```
source/vibe/core/net.d(378,68): Deprecation: returning `&this.addr` escapes a reference to parameter `this`
source/vibe/core/net.d(378,29):        perhaps annotate the function with `return`
```

Annotate `inout` functions with `return`

---

CHANGELOG.md
source/vibe/core/core.d

Will self merge in case the CI disagrees so that we get less spam while building Vibe.d.
There's still:
```
source/vibe/core/stream.d(168,29): Deprecation: scope variable `state` may not be thrown
```

Changelog / version bump for v1.22.4

---

source/vibe/core/core.d

If the event processing that gets triggered results in another call to yield every time, for example due to a fast repeating timer, `yield()` may otherwise end up calling itself indirectly indefinitely.

Avoid a possible infinite recursion in yield()

---

source/vibe/core/core.d
source/vibe/core/taskpool.d
tests/0-tcp.d
tests/0-tcpproxy.d
tests/issue-161-multiple-joiners.d
tests/issue-267-pipe.d
tests/issue-66-yield-eventloop-exit.d
tests/std.concurrency.d
tests/vibe.core.concurrency.1408.d
tests/vibe.core.core.1590.d
tests/vibe.core.core.1742.d
tests/vibe.core.core.refcount.d
tests/vibe.core.net.1376.d
tests/vibe.core.net.1429.d
tests/vibe.core.net.1441.d
tests/vibe.core.net.1726.d
tests/vibe.core.process.d

All uncaught exceptions in task callbacks haven't been handled since a long time. This removes the compatibility overloads and only keeps the ones enforcing nothrow.

Remove all task functions that take a throwing callback.

---

source/vibe/core/file.d
source/vibe/core/log.d
source/vibe/core/net.d
source/vibe/core/process.d
source/vibe/core/stream.d
source/vibe/internal/async.d
source/vibe/internal/traits.d
tests/vibe.core.stream.pipe.d

Still has one warning that complains about passing a `scope` inferred argument to `runWorkerTask`. The cause seems to be the same as for #316, namely, all members of the passed struct value are also treated as if they had a `scope` in front of them. Since there is a class reference contained inside the struct, the memory of the class instance is suddenly also treated as `scope`.
**This PR contains breaking changes in `OutputStream` and `vibe.core.process`, which will require bumping to 2.0.0 for the next release**

Fix almost all remaining scope related warnings

---

source/vibe/core/net.d
tests/0-tcp.d

The existing `releaseHandle()` method only reset the `m_socket` field if the release was the final one. This meant that calling `close()` during a pending read would leave the field set and thus cause another release from within the destructor. If that release came before the read operation was finished, this resulted in the underlying eventcode socket slot to be cleared before all operations had actually finished, consequently causing a crash in eventcore.

Fix TCP double release crash for concurrent close and read

---

.github/workflows/musl.yml
.github/workflows/test.yml
source/vibe/core/path.d

This prepares the code for a full removal of GenericPath.Segment and is supposed to be included in the next 1.x.x release. In the 2.x.x branch, the removal will be completed and Segment2 will be renamed to Segment (keeping an alias for some backwards compatibility).
Note that this is a cherry pick from master (a460e7952a9358ae4b7c7a7447fd7af1b17a5164).

Deprecate GenericPath.Segment.

---

source/vibe/core/path.d

Allows to convert to string without having to import `std.conv` explicitly. The bi-directional range also enables various operations, such as `std.algorithm.searching.endsWith`.

Let GenericPath.Segment.name return a bi-directional range with toString

---

source/vibe/core/channel.d

Enforcing the `tryConsumeOne`/`consumeAll` API avoids potential API misuse in multiple-reader scenarios or when `Channel.close()` is called outside of the reader context.
Fixes #157

Deprecate Channel.empty and .consumeOne

---

source/vibe/core/path.d

The .to!string implementation fell back to typeof(R).stringof because the passed range was const. Using an explicit save() call fixes that.

Fix GenericPath.Segment.toString()

---

.github/workflows/test.yml

The latest LDC release makes us go over the limit on MacOS.

Raise CI timeout from 15 to 30 minutes

---

source/vibe/core/sync.d
source/vibe/core/task.d

This makes it possible to properly construct `Task(Mutex/Condition)` objects as shared in order to pass them between threads. A major part missing for the longer term is replacing the current non-`shared` "Lockable" interface with a `shared` (and partially `nothrow`) one, but this will require backwards-incompatible changes. This will then also remove the need for the `@trusted` conversions.

Add shared overloads of most mutex/condition methods

---

source/vibe/core/core.d

This also makes parallelUnorderedMap nothrow.

Mark workerTaskPool and logicalProcessorCount properties safe/nothrow.

---

source/vibe/internal/freelistref.d

The compiler doesn't infer nothrow, possibly due to allocations in the "in" contract.

Force struct based FreeListRef construction to be nothrow.

---

source/vibe/core/taskpool.d

The current trigger behavior for "single" notifications sometimes resulted in all tasks ending up in the same worker thread, even if that thread was constantly busy. By notifying all threads, we do introduce a little overhead for each task, but guarantee that a worker thread that is not currently busy takes the task.

Work around unfair event object behavior in eventcore

---

source/vibe/core/core.d
source/vibe/core/task.d

Fiber.shutdown() calls Fiber.call(), which will crash if the caller is the same fiber. This now lets the fiber exit itself directly if there is no space for recycling. Regression introduced by e877c5b6690a61026e1e651bebe32e69dccea338.

Fix possible fiber self-call in recycleFiber

---

source/vibe/core/stream.d

Heavy parallel allocation of medium sized buffers can cause very large, persistent growth of GC pool memory. Since `theAllocator` is a `GCAllocator` by default, `pipe()` was one of the culprits for this behavior.

Use Mallocator instead of "theAllocator" in pipe() to reduce GC pressure

---

source/vibe/internal/array.d

The newly introduced "withAlloc" wrapper was not accepting arguments by reference, thus discarding the new array value returned by reallocate().

Fix buffer growth in AllocAppender

---

source/vibe/internal/string.d

The version in vibe-d:utils infers as safe and various places rely on that.

Make formatAlloc inferred as safe

---

source/vibe/internal/interfaceproxy.d
source/vibe/internal/string.d

Recent versions of std.experimental.allocator are using RCIAllocator instead of IAllocator for passing around allocator objects. This changes the code to accept an arbitrary type to avoid any concrete type dependence.

Make the code work for RCIAllocator

---

source/vibe/core/net.d

While building a project depending on vibe-http,
I got the following deprecation message:
```
vibe-core/source/vibe/core/stream.d(189,7):        scope variable `source` calling non-scope member function `TCPConnection.~this()`
```
Fixing the issue with the destructor shifts it to the postblit, so both needs to be fixed. The same fix was applied to the UDPConnection as a result.

Make TCPConnection/UDPConnection postblit/dtor scope

---

source/vibe/core/channel.d
source/vibe/core/file.d

To silence a deprecation message while building.

Make a ListDirectoryRequest variable scope

---

dub.sdl
source/vibe/core/task.d

Prefers logFatal over stderr.writeln so that the error also ends up in log files that may be configured. Also displays a message box for subsystem "windows" executables that don't have a console attached.

Ensure uncaught throwables in task fibers are visible to the user

---

source/vibe/core/task.d

This also prints the file and line number, making it more useful in cases where the stack trace is not usable.

Log Throwable.toString() instead of just Throwable.msg/info

---

source/vibe/core/log.d

Fixes https://github.com/vibe-d/vibe-http/pull/36

Fix lazy evaluation of log arguments

---

source/vibe/core/path.d

Otherwise it results in the following error:
```
source/vibe/core/path.d(69,17): Error: none of the overloads of `__ctor` are callable using a `immutable` object
source/vibe/core/path.d(449,2):        Candidates are: `vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.this(string p)`
source/vibe/core/path.d(461,2):                        `vibe.core.path.GenericPath!(PosixPathFormat).GenericPath.this(Segment segment)`
source/vibe/core/path.d(473,2):                        `__ctor(R)(R segments)`
source/vibe/core/path.d(148,51): Error: template instance `vibe.core.path.relativeTo!(immutable(GenericPath!(PosixPathFormat)))` error instantiating
```
@s-ludwig : This prevents `dub` from merging https://github.com/dlang/dub/pull/2272

Make relativeTo work with const paths

---

source/vibe/core/log.d

Rework SyslogLogger to be thread-safe and ensure that loggers don't yield execution

---

source/vibe/core/log.d

This prepares for a broader fix of the `Logger` interface and avoids having to make a breaking API change later on.

Let createSyslogLogger return a shared object

---

.github/workflows/test.yml
dub.sdl
source/vibe/core/file.d
source/vibe/core/log.d
source/vibe/core/task.d
source/vibe/internal/async.d

Affects the CI of the vibe.d repository

Fix CI errors and unittest compile error on certain compiler versions

---

source/vibe/core/file.d
tests/vibe.core.file.d

Closing of the file stream must only be done when the last reference gets destroyed.
Note that this requires an API addition in eventcore, which is why the code has been wrapped in a static if.

Fix a regression introduced by #411

---

source/vibe/core/file.d

The warning in its previous form was too general. It is only an actual problem if the last reference to a FileStream is leaked to the GC, as long as it is ensured that the file gets closed before the GC attempts to finalize the last copy, everything is safe.
See #412

Fix bogus FileStream destruction warning.

---

source/vibe/core/concurrency.d
source/vibe/core/core.d
source/vibe/core/internal/threadlocalwaiter.d
source/vibe/core/sync.d

This improves code separation between `ManualEvent` and `ThreadLocalWaiter` to improve algorithmic clarity.

Mostly refactoring of ManualEvent/ThreadLocalWaiter

---

source/vibe/core/sync.d

Using non-D threads to trigger ManualEvents should work without creating a thread instance of an event driver in the triggering thread. Using an event driver in such a thread leads to possible memory errors (because references to the driver instance are not visible to the GC) and leaks resources (event/socket pair handles) to the GC.

Avoid unnecessarily creating event driver instances in non-D threads.

---

source/vibe/core/net.d

We have lack of support IPv6 addresses formatting, and especially, IPv4 addresses encapsulated into IPv6
[This code](https://github.com/vibe-d/vibe-http/blob/338ecb4b6aeaf6b9f49a9cd1f550c9d670a1299d/source/vibe/http/server.d#L959) is never called and IPv4 addresses on IPv6 interfaces logged as `0:0:0:0:0:ffff:bca2:ee5` instead of `::ffff:188.162.14.229`
I made own implementation because `inet_ntop` from glibc internally does redundand buffer copying, uses stringz, errno and not handles ~~rare `::2` address case~~

Improves IPv6 addresses formatting

---

source/vibe/core/path.d

We have a copy of this module in Dub which forwards to this function while wrapping GenericPath and this special case hit us.

refactor: Make relativeTo more copy-paste friendly

---

tests/issue-58-task-already-scheduled.d

This seems to be the cause of an issue in Buildkite, and looking at the code, there was a deprecation a few months back to force nothrow on delegate arguments, however this does not seem to be caught by the regular CI.

fix: Make an argument to runWorkerTask nothrow

---

source/vibe/core/file.d
source/vibe/core/path.d

- Swaps the implementation and documentation of `.normalize` and `.normalized`
- Avoids allocations when normalizing an already normalized path
- Deprecates `.Segment2` and associated methods

GenericPath cleanup

---

source/vibe/core/file.d
source/vibe/core/sync.d

Was using Task.getThis() to identify the current lock owner, which would be Task.init outside of a task. Using TaskFiber.getThis() instead, which returns a dummy fiber instance if called outside of a fiber, so that it can be distinguished from TaskFiber.init meaning no owner.

Fix RecursiveMutex to work outside of tasks and make lock() nothrow.

---

source/vibe/core/file.d

Fix the buffer returned by `readFile` being erroneously scanned by the GC

---

source/vibe/core/log.d

Avoids Exception.toString() and instead logs the diagnostic pieces one-by-one, avoiding dynamic memory allocations and and printing out as much as possible in case of a secondary failure during logging.
Also now never logs the diagnostic part of the exception with a log level higher than the main message.

Improve logException robustness
