.codecov.yml
.gitignore
.travis.yml
travis-ci.sh

Similarly to https://github.com/rejectedsoftware/vibe.d/pull/1804

Add initial CodeCov setup

---

source/vibe/core/sync.d

Also adds assertions and a randomized multi-thread test to rule out similar issues with a higher confidence.

Fix double-free of ThreadLocalWaiter in ManualEvent.

---

dub.sdl
source/vibe/core/net.d

Implement the UDP multicast support methods.

---

source/vibe/core/net.d
source/vibe/internal/async.d

This fixes #41 by rebasing on top of the latest master. It includes the Optlink workaround, which, although master now passes without it, is necessary to compile the library on Windows with Optlink for DMD < 2.077.0.

Rebased version of "tcp connect timeout" with Optlink fix

---

appveyor.yml

This should hopefully get rid of the frequent failures on AppVeyor.

Update DUB on AppVeyor to 1.7.1

---

source/vibe/core/core.d

Use std.parallelism.totalCPUs to implement logicalProcessorCount.

---

source/vibe/core/task.d

Requires -debug=VibeTaskLog to enable them now.

Make high-frequency log messages in the task scheduler optional.

---

appveyor.yml
source/vibe/core/core.d
source/vibe/core/task.d
tests/issue-58-task-already-scheduled.d

Fix unscheduling tasks when resuming from outside of a task.

---

source/vibe/core/connectionpool.d

ConnectionPool!TCPConnection used to work with the old vibe-d:core implementation, but now failed, because TCPConnection is a struct. All assumptions about `Connection` being a class have been remove in this commit.

Fix compilation of ConnectionPool!struct. Fixes vibe-d/vibe.d#2109.

---

source/vibe/core/net.d

MonoTime is more robust and does not involve sophisticated timezone
shenanigans, making it better suited for networking operations.
Fixes #39.
This commit also distinguishes read timeout exception as Exception child
ReadTimeoutException, wich is thrown from loopWithTimeout function.
Optimistic read branch for tcp socket improves performance on
granular reads.

MonoTime in loopWithTimeout, and other read tweaks.

---

.travis.yml

Analogous to https://github.com/vibe-d/vibe.d/pull/2140

Install the newest version of dub to avoid random network failures

---

source/vibe/core/core.d

The exit flag was erroneously set, disabling any event processing during yield() calls when not inside an event loop.

Fix event processing when calling yield() outside of an event loop.

---

source/vibe/core/log.d

Fix host name conversion code for SyslogLogger

---

source/vibe/core/core.d
tests/issue-104-unreferenced-periodic-timer.d

Fix unreferenced periodic timers

---

source/vibe/core/file.d
source/vibe/core/sync.d
tests/vibe.core.net.1429.d

same as https://github.com/vibe-d/eventcore/pull/96

Use monotonic clock for timeout

---

source/vibe/core/net.d

Use a robust check IP vs. host name check for resolveHost

---

tests/issue-115-connect-fail-leak.d

Make the test for #115 actually fail if a socket gets leaked.

---

source/vibe/core/core.d
source/vibe/core/task.d

Improve timer documentation and add a yieldLock the callback invocation

---

source/vibe/core/core.d
source/vibe/core/taskpool.d

Variant of runWorkerTask that allows to get the handles of the created tasks.

Implement runWorkerTaskDistH.

---

source/vibe/core/channel.d
source/vibe/core/sync.d

The branch is based on #129, which should be merged first.
- Makes the API more `@safe` and `nothrow`
- Adds `Channel.bufferFill`

Channel improvements

---

source/vibe/core/net.d

Fix #109 - TCPConnectionFunction is actually a delegate

---

source/vibe/core/file.d

Avoids listDirectory/iterateDirectory getting interrupted when stumbling over inaccessible files. The `name` field of the returned file info value is always set, so that these files can still be identified.

Make the DirEntry->FileInfo conversion nothrow.

---

source/vibe/core/sync.d
source/vibe/core/task.d

Fixes a race-condition reported by LDC's thread sanitizer, as well as implementing thread-safe task joining and interruption.

Threading fixes

---

dub.sdl
source/vibe/core/net.d

Provides a proper basis for #153

Add TCPConnection.waitForDataEx

---

source/vibe/core/net.d

Let TCPConnection.leastSize time out according to the readTimeout property

---

source/vibe/core/channel.d
tests/issue-157-consume-closed-channel.d

Fix empty-consumeOne channel usage pattern for a single consumer

---

source/vibe/core/connectionpool.d

Same as with this [PR](https://github.com/vibe-d/vibe.d/pull/2340)

unlock ConnectionPool on failure

---

source/vibe/core/file.d

FileStream: Adjust file offset when appending to a file

---

source/vibe/core/path.d
source/vibe/internal/string.d

In support of https://github.com/dlang/druntime/pull/2777

Replace `hash_t` and `sizediff_t` with `size_t` and `ptrdiff_t`

---

source/vibe/core/path.d

This adds `GenericPath.bySegment2`, which returns segmends that hold the encoded segment name instead of the decoded one. `Segment2.name` also returns a `@nogc` range, so that all read operations work without allocations now.
Unfortunately it was not possible to change the existing implementation and to keep the old name. Instead, the plan here is to deprecate `bySegment` after the next version and replace it by `bySegment2` in 2.0.0.

Add a nogc path segment API

---

source/vibe/core/core.d

Uninitialized YieldLock values can happen in various ways, dispite the default constructor being disabled. If any such value got destroyed, it would lead to a negative lock count. Since this is handled properly now, the default constructor is also enabled in this commit.

Make sure that an uninitialized YieldLock does not decrement the lock counter

---

source/vibe/core/log.d

This was not working at all since the release of vibe-core due to dependencies on other parts of vibe.d. The unit test has now been moved out of the template class, so that it is actually run.

Fix SyslogLogger. Fixes #203.

---

.travis.yml
CHANGELOG.md
appveyor.yml
dub.sdl
travis-ci.sh

Also requires at least eventcore 0.9.2 to work.

Add "cfrunloop" configuration for macOS.

---

source/vibe/core/net.d

I'm not sure how to write a test-case for this though.

Add optional timeout parameter to resolveHost

---

tests/args.sh

Workaround dub build by using `--single` in the test

---

.travis.yml
CHANGELOG.md
source/vibe/core/core.d
source/vibe/core/log.d
source/vibe/core/net.d
source/vibe/core/task.d
source/vibe/core/taskpool.d
tests/0-tcpproxy.d

See each commit for the description of what they do.

Improve logging routines by using > 2.079 feature

---

source/vibe/core/file.d
source/vibe/core/task.d
source/vibe/internal/hashmap.d

This will allow users to use -preview=in as soon as it's released.

Add support for DMD 2.094 -preview=in switch

---

source/vibe/internal/interfaceproxy.d

Previously caused crashes and opCast!bool to return true for null instances.

Fix InterfaceProxy to work with null values.

---

source/vibe/core/task.d

Calling Task.interrupt() on a task that is already finished, but ran on the same fiber would trigger an assertion failure instead of returning silently.

Avoid bogus "A task cannot interrupt itself" assertion failure.

---

source/vibe/core/file.d

Makes sure that `FindClose` gets called before `listDirectory` returns to avoid a race-condition, where a successive modification of the directory fails with "access denied".

Fix bogus file access denied error after listDirectory calls on Windows

---

source/vibe/core/stream.d

Reduces overhead for fast streams by increasing the buffer size up to 4MB, as long as the latency stays below 100ms.

Allow the buffer to grow for PipeMode.concurrent.

---

source/vibe/core/core.d

This fixes a regression introduced by #98 and 03ffe70dc1f583276b729bd7b5baa68bbdca0906, which lead to a new independent task being created per timer invocation instead of invoking the callbacks in a single loop.

Ensure that a timer callback is never invoked concurrently.

---

source/vibe/core/core.d

Fairly simple, but I had to test it to figure out the behavior, instead of just looking up the docs.

Improve documentation for setTimer and sleep

---

source/vibe/core/core.d

Fix periodic timer callbacks firing after calling Timer.stop().

---

source/vibe/core/core.d

Since the m_running logic was executed in a task instead of synchronously, it could happen that it got executed right after a call to Timer.stop(), erroneously starting up another callback task.

Fix a possible timer callback call happening after Timer.stop()

---

source/vibe/core/core.d

Bump version to v1.14.0

---

source/vibe/core/channel.d
source/vibe/core/core.d
source/vibe/core/sync.d
source/vibe/core/taskpool.d

- Channel construction
- TaskCondition construction
- workerThreadCount and setupWorkerThreads
- TaskPool creation

Make more APIs nothrow

---

source/vibe/internal/traits.d

makes it obvious in which modules types are for quicker troubleshooting.
The `from T` isn't as accurate as it could be (doesn't show inheritance of interface / only shows the passed interface and not anything it was inherited from) but it's good enough to find issues.

print interface conformance errors with FQN

---

source/vibe/core/task.d

Mark TaskFiberQueue insert functions trusted

---

source/vibe/core/file.d
source/vibe/core/stream.d

Forms the new basis for FileStream to be able to support other file-like stream types.

Add ClosableRandomAccessStream

---

source/vibe/core/net.d

Was looking at this module and figured it could use a bit of love.

Slightly improve documentation in `vibe.core.net`

---

source/vibe/core/concurrency.d

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

feat(concurrency): add .task() property on Future struct

---

.github/workflows/musl.yml
.github/workflows/test.yml

https://github.com/vibe-d/vibe.d/pull/2688

Update actions/checkout in GitHub Actions to v3

---

source/vibe/core/task.d

Avoids assert errors, because those GC-allocate, and adds checks before Fiber.call().

Improve finalizer yield checks.

---

source/vibe/core/core.d
source/vibe/core/task.d

Expose timeout on runEventLoopOnce

---

source/vibe/core/core.d
source/vibe/core/file.d
source/vibe/core/stream.d
source/vibe/internal/interfaceproxy.d

This also fixes #316 and closes #317.

Fix scope related deprecation warnings

---

source/vibe/core/net.d
tests/issue-331-tcp-connect-timeout.d

Fix TCP connect timeout leaks

---

.github/workflows/test.yml
README.md
run-ci.sh
source/vibe/core/net.d
source/vibe/core/process.d
tests/args.sh
tests/issue-110-close-while-waitForData.d
tests/issue-157-consume-closed-channel.d
tests/issue-267-pipe.d
tests/vibe.core.process.d

These have been accidentally disabled when switching to GitHub actions due to the runner using PowerShell instead of Bash.

Fix Windows CI runs

---

source/vibe/core/path.d

This prepares the code for a full removal of GenericPath.Segment and is supposed to be included in the next 1.x.x release. In the 2.x.x branch, the removal will be completed and Segment2 will be renamed to Segment (keeping an alias for some backwards compatibility).

Deprecate GenericPath.Segment

---

source/vibe/core/path.d

This completes the migration to Segment2 by renaming it to Segment, while keeping a backwards compatibility alias. Any code that used Segment2 will continue to work as-is, while code based on Segment may need some adjustments to explicitly convert the .name property to a string.

Remove GenericPath.SegmentOld and associated code.

---

source/vibe/core/core.d
source/vibe/core/file.d

Reduces contention between CPU and I/O workloads. Note that only certain I/O operations, such as listing directories, are subject to this change. Data read/write operations are instead handed by eventcore.

Use a separate thread pool for I/O operations.

---

examples/echo-server/dub.sdl
examples/echo-server/source/app.d
source/vibe/core/net.d
tests/tcp-read-timeout.d

This PR is the squashed version of #359 by @dushibaiyu, with an additional fix for the new test case.

TCPConnection.read(buffer,IOMode.once) should throw ReadTimeoutException

---

source/vibe/core/sync.d

Avoids an assertion failure/abort() when a ThreadWaiter gets destroyed by the GC in the wrong thread. A warning is still generated, as this indicates that a thread was still waiting on a ManualEvent at runtime termination time and thus was not shut down properly.

Handle GC leaks of ManualEvent/ThreadWaiter gracefully

---

source/vibe/core/connectionpool.d

This restriction is not compatible with task based stream processing, such as when using pipe() on concurrent mode. In particular, for HTTPClientResponse, this would trigger the end callback from pipe()'s read task, which in turn would finalize the response object, including the locked connection instance it contains.

Remove task check from LockedConnection.

---

source/vibe/internal/array.d

Up to now, was relying on the old stdx.allocator interface that used IAllocator for passing around allocators as objects. The current version uses RCIAllocator instead.

Make AllocaAppender forward compatible with current std.experimental.allocator

---

source/vibe/core/file.d

On the device, the /tmp folder is not accessible for regular apps on iOS. `NSTemporaryDirectory` returns a usable directory instead.

Use the correct temporary folder on iOS

---

source/vibe/core/core.d

Uses RAII to guarantee that none of the contained tasks can outlive the scope of the task group.

Add TaskGroup as a means to limit task lifetime to a scope
